[project]
name = "auto-screen"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "notebook>=7.4.0",
    "pandas>=2.2.3",
    "polars>=1.27.1",
    "synergy-dataset>=1.2",
]
